### PR TITLE
8278869: Bump version numbers for OPENJDK 18.0.1

### PR DESCRIPTION
**Pull request by pashh**
Bump version numbers for JDK 18.0.1

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Integration blocker
&nbsp;⚠️ Failed to retrieve information on issue `8278859`. Please make sure it exists and is accessible.

### Issue
 * ⚠️ Failed to retrieve information on issue `8278859`.

### Reviewers
 * [Sean Coffey](https://openjdk.java.net/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk18u pull/1/head:pull/1` \
`$ git checkout pull/1`

Update a local copy of the PR: \
`$ git checkout pull/1` \
`$ git pull https://git.openjdk.java.net/jdk18u pull/1/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1`

View PR using the GUI difftool: \
`$ git pr show -t 1`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk18u/pull/1.diff">https://git.openjdk.java.net/jdk18u/pull/1.diff</a>

</details>

### CODE REVIEW

**Review by coffeys — APPROVED** [review]

**Comment by kevinrushforth** [comment]
@pashh for future reference, it would have been easier to just change the title of this PR rather than creating a new one.

**Comment by kevinrushforth** [comment]
Hmmm. I see that you already did that. In that case, I'm puzzled as to why you closed it?

**Comment by coffeys** [comment]
Still marked as open in JBS @pashh  
Please clarify

Do you need this to be sponsored ?

**Comment by kevinrushforth** [comment]
Fir reasons that aren't at all clear to me, he closed this one and opened a new PR -- #2

**Comment by coffeys** [comment]
> Fir reasons that aren't at all clear to me, he closed this one and opened a new PR -- #2

Thanks @kevinrushforth  - I'll approve that one also since it's in the system now.  We might chose to remove the old review PR link from the JBS report.

**Pull request closed without merging**
